### ISSUE TITLE
Assets output

### ISSUE THREAD

**Issue by bskimball** [bskimball/nuxtober#1]
Assets are not being output correctly. Need to alter the webpack config.

**Comment by bskimball** [comment]
changed the distNuxtPath to process.cwd() + "\\assets\\"

**Comment by Almusamim** [comment]
In case we don't want to bother with the theme directory name and changing it in two places.. what do you think about using something like publicPath: themeAssets ? 

`const themeAssets = '/themes/'+__dirname.split(path.sep).pop()+'/assets/';`

or is it just too ugly?

**Comment by bskimball** [comment]
That's a good idea, we can put it directly in the module.
